-- MySQL Script generated by MySQL Workbench
-- Sun Mar 26 04:06:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_tugas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_tugas` ;

-- -----------------------------------------------------
-- Schema db_tugas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tugas` ;
USE `db_tugas` ;

-- -----------------------------------------------------
-- Table `db_tugas`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tugas`.`user` ;

CREATE TABLE IF NOT EXISTS `db_tugas`.`user` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_tugas`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_tugas`;
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A1, 'Ahmad sofyan', 'ahmad2@gmail.com', 09877678890, 'L', 'depok ');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A2, 'Afwan fajar', 'afwan3@gmail.com', 09878281997, 'L', 'makasar');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A3, 'Amelia putri n ', 'amelptr9@gmail.com', 087654621816, 'P', 'kalisari');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A4, 'Amira dalillaturadwa', 'amiralila32@gmail.com', 086547762543, 'P', 'depok');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A5, 'Alfiana ilmi s', 'alfiana@gmail.com', 08764321345, 'P', 'bambu apus');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A6, 'Alfidzi pahlawan', 'aliifyzy@gmail.com', 9876875656, 'L', 'bambu apus');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A7, 'Alamsyah putra', 'almput@gmail.com', 09883736453, 'L', 'kalisari');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A8, 'Aryodamar Ananta', 'aryodmr21@gmail.com', 08765345267, 'L', 'lubang buaya');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A9, 'Dinda safitri', 'dindaa@gmai.com', 09876553435, 'P', 'ciracas');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A10, 'Difka salsabila', 'difkasl3@gmail.com', 087645324123, 'P', 'duren wasit');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A11, 'Dandi fikri', 'dandi7@gmail.com', 08765423128, 'L', 'cibubur');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A12, 'Eliza ayu andini', 'eeliza8@gmail.com', 08953876291, 'P', 'dukuh');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A13, 'Febriana puspita', 'febriary@gmail.com', 08954672131, 'P', 'pekayon');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A14, 'Fathur rahman', 'fathurzoy@gmail.com', 086756213324, 'L', 'depok');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A15, 'Faizal daffa', 'faisaldaf@yahoo.com', 08776665566, 'L', 'pekayon');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A16, 'Gilang ramadhon', 'gildon@gmail.com', 08545267112, 'L', 'ciracas');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A17, 'Hafiz farhan', 'hafiz22@gmail.com', 08976564324, 'L', 'dukuh');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A18, 'Helwa ', 'hlwaa@yahoo.com', 08234576543, 'P', 'ciracas');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A19, 'Imam ghifari', 'ghifa5@gmail.com', 09782765518, 'L', 'gedong');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A20, 'Imansyah', 'iammn@gmail.com', 08657754555, 'L', 'ciracas');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A21, 'Izar hairul', 'izarhg6@gmail.com', 08565777887, 'L', 'cilodong');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A22, 'Jull effendi', 'ijull@gmail.com', 08567898865, 'L', 'ciracas');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A23, 'Khaly kawarismi', 'olly@gmail.com', 09977654444, 'L', 'kallisari');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A24, 'Maya handayani', 'mayarfr@gmail.com', 08967542223, 'P', 'ciracas');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A25, 'Mutia tri', 'mute@gmail.com', 08876656655, 'P', 'ciracas');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A26, 'Munawaroh', 'munnan@gmail.com', 08765455332, 'P', 'pinang ranti');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A27, 'Rudi hermawan', 'rudii45@gmail.com', 08567844323, 'L', 'pasar rebo');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A28, 'Sekar maharani', 'sekaryu@gmail.com', 07676743241, 'P', 'lubang buaya');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A29, 'Siska fauzi', 'cika@yahoo.com', 08776753124, 'P', 'kalisari');
INSERT INTO `db_tugas`.`user` (`user_id`, `name`, `email`, `phone`, `gender`, `address`) VALUES (A30, 'Ragil rahmawati', 'rahill56@gmail.com', 08976554321, 'P', 'ciracas ');

COMMIT;

